### ISSUE TITLE
Funding source/pulication create page missing button to cancel

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#63]
The funding source 
http://localhost:8000/en/funding/add-funding-source/?_popup=1
and publications
http://localhost:8000/en/funding/create-publication/?_popup=1
pages have no back or cancel buttons.

Having to resort to something outside of the web UI (e.g. close window buttons) could be confusing to some users.

This could be accomplished relatively easily with a callback on an anchor, which seems worth the effort.

**Comment by edbennett** [comment]
Not sure what a callback on an anchor is (everything is pointing me towards Seaside, which I'd rather be at, but that's not the point here), but I've implemented this by identifying popups by naming the window, and then checking for this name in a bit of javascript and displaying the close button if the name is found. When javascript is disabled, the page is loaded directly rather than as a popup, and the close button isn't displayed.
