### ISSUE TITLE
What are the funding source membership routes and logic?

### ISSUE THREAD

**Issue by markgdawson** [edbennett/cogs3#91]
It isn't clear to me what the togglefundingsourcemembershipapproved route does, e.g.:
/en-gb/funding/togglefundingsourcemembershipapproved/<id>

It seems to redirect to:
/en-gb/funding/list/

Potentially just permissions guards, but I have not tested/investiaged this.

**Comment by markgdawson** [comment]
It seems that funding can belong to multiple users, but only one project.

Presumably the intention was to allow each user to add funding source to their projects. This is not the case.

There are 3 options that I can see:
- prevent users from having multiple funding source
- prevent funding sources from belonging to multiple projects.
- remove funding source membership table

There is also a one-to one relationship (currently) between projects and funding sources.

The argument for keeping funding source membership table is that we would have a system where a funding source has multiple users, and the multiple users are permitted to add the funding source to multiple projects.

A much simpler implementation could be that each funding source (which potentially has an owner which manages it) can be added to multiple projects.

This would be much, much simpler - but has the downside that multiple people can't allocate/deallocate the projects on any given funding source. I'm not sure that this is worth the considerable complexity of the funding membership workflow.

The funding membership implementation isn't particularly clean anyway, and could be done much simpler.

**Comment by edbennett** [comment]
> There is also a one-to one relationship (currently) between projects and funding sources.

https://github.com/M4rkD/cogs3/blob/9cbe980a89e766d9a5e024e37480c2ca9f017916/project/models.py#L115 suggests otherwise?

> A much simpler implementation could be that each funding source (which potentially has an owner which manages it) can be added to multiple projects.

What would the UI for this look like? All users can see every funding source on the system to potentially add to their projects? The intent of having users be "members" of a funding source was that they would only have visibility of funding sources they had indicated they wanted to use by supplying an ID code for it; I can't see how you'd implement this without something resembling what we have now.
